baseURL = "/"
languageCode = "en-gb"
title = "Porting Linux to CHERI"
themesDir = "themes"
theme = "whisper-2023-11-26"

pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
pygmentsUseClasses = true

[module]
  [module.hugoVersion]
    extended = true
    min = "0.55.0"

# Controls how many words are printed in the content summary on the docs homepage.
# See https://gohugo.io/content-management/summaries/
summaryLength = 30

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

[[menu.main]]
    name = "Docs"
    url = "/docs/"
    weight = 2

[params]
  google_analytics_id=""
  homepage_button_link = 'docs'
  homepage_button_text = 'Read The Docs'
  homepage_intro = 'Enhancing Linux with CHERI security.'
  homepage_image = 'images/cheri_tux.svg'

  ## You can enable to add anchor links to header elements
  enable_anchor_link = true

  [params.homepage_meta_tags]
    meta_description = "Linux enhanced with Capability Hardware Enhanced RISC Instructions (CHERI) security."
    meta_og_title = "Porting Linux to CHERI"
    meta_og_type = "website"
    meta_og_url = ""
    meta_og_image = ""
    meta_og_description = "Enhancing Linux with Capability Hardware Enhanced RISC Instructions (CHERI) security."
    meta_twitter_card = "summary"
    meta_twitter_site = ""
    meta_twitter_creator = ""

  [params.logo]
      mobile = "images/cheri_logo.svg"
      standard  = "images/cheri_logo.svg"
